name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Deploy with SCP
      uses: appleboy/scp-action@v0.1.4  # Correct version for the SCP action
      with:
        host: localhost
        username: sphere               # Replace with your actual SSH username
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: ./dist/*               
        target: /var/www/my-vite-app/  
        port: 22
        sync: false
